---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(siga)
library(data.table)
library(ggplot2)
```

```{r}
read_data <- function() {
  # Lee los datos y los combina
  files <- list.files(here::here("datos"), full.names = TRUE, pattern = ".txt") 
  datos <- lapply(files, data.table::fread, na.strings = "-99.9")
  
  data <- data.table::rbindlist(datos)[, date := as.Date(date)]
  data <- data.table::as.data.table(tidyr::complete(data, station_id, date))[]
  
  return(data)
}

read_metadata <- function() {
  # Lee los metadatos de estación
  datos <- data.table::fread(here::here("datos", "METADATA_1960-2012.csv"))
  datos[, .(station_id, name, lon, lat, elev)]
}
```

```{r}
claris <- read_data() 

meta <- read_metadata()

arg <- rnaturalearth::ne_countries(country = c("Argentina", "Paraguay"), return = "sf")
```

```{r}
claris[, let(delta_t = tmax - shift(tmax, n = 1)), by = station_id] |> 
  # _[]
  _[, let(t_fall = delta_t <= -10)]

claris[, .(na = sum(is.na(t_fall))/.N), by = station_id] |> 
    meta[i = _, on = "station_id"] |> 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = na*100), alpha = 0.5) +
  geom_point(data = ~.x[na*100 > 5], shape = 21, fill = NA) +
  scale_color_viridis_c( guide = guide_colorbar(barwidth = 0.5,
                                               barheigh = 15)) +
  geom_sf(data = arg, inherit.aes = FALSE, fill = NA) +
  labs(x = NULL, y = NULL, color = NULL) +
  theme_minimal()

claris |> 
  ggplot(aes(date, factor(station_id))) +
  geom_tile(aes(fill = is.na(t_fall))) +
  scale_fill_manual(values = c("black", "grey")) +
  labs(y = "Station ID", fill = "Is NA?") +
  theme_minimal()
```

```{r}
claris |> 
  _[, .(n_front = sum(t_fall, na.rm = TRUE)), by = .(year(date), station_id)] |>
  ggplot(aes(year, n_front)) +
  geom_line(aes(group = station_id))
```

```{r}
ids <- claris |> 
  _[, .(n_front = sum(t_fall, na.rm = TRUE)), by = .(year(date), station_id)] |> 
  _[, .(mean_front = mean(n_front)), by = station_id] |> 
  meta[i = _, on = "station_id"] |> 
  _[mean_front >= 6, station_id]

claris[station_id %in% ids] |> 
  _[, .(n_front = sum(t_fall, na.rm = TRUE)), by = .(year(date), station_id)] |>
  _[, let(n_front_mean = frollmean(n_front, 5, align = "center")), by = station_id] |>
  ggplot(aes(year, n_front)) +
  geom_line(aes(group = station_id)) +
  geom_line(aes(y = n_front_mean), color = "orange") +
  facet_wrap(~station_id) +
  labs(x = NULL, y = "Number of t falls") +
  theme_minimal()
```

```{r}


claris |> 
  _[, .(n_front = sum(t_fall, na.rm = TRUE)), by = .(year(date), station_id)] |> 
  _[, .(mean_front = mean(n_front)), by = station_id] |> 
  meta[i = _, on = "station_id"] |> 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = mean_front)) +
  scale_color_viridis_c(breaks = seq(1, 9, 1), guide = guide_colorbar(barwidth = 0.5,
                                               barheigh = 15)) +
  geom_sf(data = arg, inherit.aes = FALSE, fill = NA) +
  labs(x = NULL, y = NULL, title = "Mean days per year", color = NULL) +
  theme_minimal()
```

```{r}
claris |> 
  _[delta_t < 0] |> 
  ggplot(aes(delta_t)) +
  geom_histogram(binwidth = 0.5)

claris |> 
  _[, .(p95 = quantile(delta_t, 0.02, na.rm = TRUE)), by = station_id] |> 
   meta[i = _, on = "station_id"] |> 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = p95)) +
  scale_color_viridis_c(breaks = seq(-12, -5, 1), guide = guide_colorbar(barwidth = 0.5,
                                               barheigh = 15)) +
  geom_sf(data = arg, inherit.aes = FALSE, fill = NA) +
  labs(x = NULL, y = NULL, title = "p98 threshold", color = NULL) +
  theme_minimal()


```

```{r}
claris_eof <- claris |> 
  _[, let(delta_t = fifelse(is.na(delta_t), 0, delta_t))] |> 
  metR::EOF(delta_t ~ date | station_id, n = 1:5, data = _)


claris_eof$right |> 
  _[, .SD[which.max(delta_t), ], by = station_id] |> 
   meta[i = _, on = "station_id"] |> 
  ggplot(aes(lon, lat)) +
  geom_point(aes(color = PC)) +
  scale_color_viridis_d() +
  geom_sf(data = arg, inherit.aes = FALSE, fill = NA) +
  labs(x = NULL, y = NULL, title = "Mean days per year", color = NULL) +
  theme_minimal()
```

```{r}
claris |> 
  # _[, let(pr_mean = mean(pr, na.rm = TRUE)), 
  #   by = .(station_id, day(date), month(date))] |> 
  # _[, let(pr_anom = pr - pr_mean)] |> 
  _[, .SD[pr > 0, .(p95 = quantile(pr, probs = 0.99))], by = station_id] |> 
  _[claris, on = .NATURAL] |> 
  _[, match := pr > p95] |> 
  # _[delta_t < -10] |> 
  ggplot(aes(delta_t, pr_anom)) +
  geom_point(aes(color = match), alpha = 0.2)
```


```{r}
claris[station_id == 10156] |> 
  ggplot(aes(delta_t, pr)) +
  geom_point()
```

